### ISSUE TITLE
AttributeError: 'OrderedDict' object has no attribute 'set_glove_path'

### ISSUE THREAD

**Issue by xinfu607** [AnnikaLindh/Diverse_and_Specific_Image_Captioning#1]
I am sorry that I meet error when runnning launch_training.py
Has infersent.set_glove_path() function been changed ?

Traceback (most recent call last):
  File "/home/Diverse_and_Specific_Image_Captioning/combined_model/SentEval/examples/launch_training.py", line 17, in <module>
    train.train(opt)
  File "/home/Diverse_and_Specific_Image_Captioning/combined_model/neuraltalk2_pytorch/train.py", line 99, in train
    pretrained_senteval_path=opt.senteval_model)
  File "/home/Diverse_and_Specific_Image_Captioning/combined_model/SentEval/examples/infersent.py", line 71, in load_senteval
    params_senteval.infersent.set_glove_path(GLOVE_PATH)
AttributeError: 'OrderedDict' object has no attribute 'set_glove_path'
Terminating BlobFetcher

**Comment by AnnikaLindh** [comment]
Hi, sorry for the delay in my reply.
I looked it up now and it turns out they removed that function from SentEval after my final pull from their repo. If you pull commit c7c7b3a then that function should still be there. Let me know if that works for you!
